# Generated by Django 5.1.6 on 2025-02-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="created_at",
        ),
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("random_thoughts", "Random Thoughts"),
                    ("personal", "Personal"),
                    ("school", "School"),
                    ("drama", "Drama"),
                ],
                default="random_thoughts",
                max_length=20,
            ),
        ),
    ]
